---
title: "Service & leadership"
format: 
  html:
    embed-resources: true
    toc: true
---


## Service

### Macalester College — Department of Mathematics, Statistics & Computer Science, Fall 25-Summer 26
As part of the Transformation Committee, I contribute across multiple areas that support both faculty and students. I am involved in preceptor hiring, training, and evaluation, with a strong emphasis on creating a sense of community. This includes designing and leading training related to diversity, equity, and inclusion (DEI), pedagogy, and departmental policies, as well as serving as a liaison to the Science and Quantitative Center.

The committee also focuses on faculty support and mentoring by ensuring that junior faculty are paired with senior mentors and that new faculty are connected with colleagues who have previously taught the same course. In addition, the committee organizes reciprocal course visits for all faculty members, encouraging these exchanges to happen early in the academic year.

Within the DEI space, as a member of the committee, I work on updating the department’s DEI website and ensuring that concrete efforts are clearly communicated. The committee also contributes to rethinking policies and procedures, scheduling student listening sessions, and maintaining community guidelines so they remain relevant and widely shared. To further pedagogical development, the committee helps initiate workshops and working groups tailored to faculty interests, and collaborate with the Student Advisory Board whenever appropriate.


## Leadership

### Michigan Technological University — Graduate Student Government (GSG) - Spring 20-23
At Michigan Tech, I held elected leadership roles in two GSG-recognized student organizations. As Treasurer and later Vice President of the Muslim Student Association (MSA) (Jan 2021–Dec 2022), I oversaw budgeting and financial reporting, submitted funding requests to GSG, coordinated campus partnerships and events, and maintained day-to-day operations and member communications—stepping in for the president when needed to keep initiatives on track. 

Earlier, as President of the Bangladesh Student Association (BSA) (Jan–Dec 2020), I led cultural and community programming, coordinated activities for a broad membership, managed administrative requirements with the university, and represented the organization in collaborations across campus. Together, these roles strengthened my capacity to manage budgets, design inclusive programming, and translate community goals into organized, well-communicated action.
